


  [build]
  publish = "build"
  functions = "netlify/functions"

[dev]
  framework = "#custom"
  command = "npm run dev"  # Команда для запуска SvelteKit
  targetPort = 5173         # Порт, на котором запускается SvelteKit

